apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.env }}-app
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.env }}-{{ .Values.component }}.{{ .Values.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
